### ISSUE TITLE
EPG Translator

### ISSUE THREAD

**Issue by frank087234** [teamblue-e2/enigma2#1]
When I install EPG translator from , pressing EPG info cause crash.

> 15:23:50.1036 { D } Traceback (most recent call last):
15:23:50.1041 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 49, in action
15:23:50.1052 { D }   File "/usr/lib/enigma2/python/Screens/EpgSelection.py", line 184, in infoKeyPressed
15:23:50.1071 { D }   File "/usr/lib/enigma2/python/mytest.py", line 323, in open
15:23:50.1095 { D }     dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
15:23:50.1099 { D }   File "/usr/lib/enigma2/python/mytest.py", line 266, in instantiateDialog
15:23:50.1120 { D }     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
15:23:50.1125 { D }   File "/usr/lib/enigma2/python/mytest.py", line 283, in doInstantiateDialog
15:23:50.1147 { D }     dlg = screen(self, *arguments, **kwargs)
15:23:50.1151 { D }   File "/usr/lib/enigma2/python/Screens/EventView.py", line 363, in __init__
15:23:50.1244 { D }     EventViewBase.__init__(self, Event, Ref, callback, similarEPGCB, parent)
15:23:50.1252 { D } TypeError: EventViewBase__init__() takes at most 5 arguments (6 given)
15:23:50.1257 [ E ] python/python.cpp:209 call [ePyObject] (CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0x72cfc120>>,('EPGSelectActions', 'info')) failed)

**Comment by arn354** [comment]
hmm works here? Do you install from regular feed?
Please provide exact rcu key presses to reproduce.

I have this one installed and get no crash.

Using username "root".
root@gbquad4k:~# opkg list-installed |grep translator
enigma2-plugin-extensions-translator - 1.1rc1
root@gbquad4k:~#

**Comment by teamblue-e2** [comment]
i see - at least a temporary workaround: https://github.com/teamblue-e2/enigma2/commit/b8c71d7fcbe1fb7c6d57ca6bde75c0f72bad33b2
