### ISSUE TITLE
teamblue 6.4-Dm520

### ISSUE THREAD

**Issue by zozman21** [teamblue-e2/enigma2#14]
After successful image building
The image only works if the skin ( gigabluepax ) is of high resolution full hd ( 1920 X 1080 )
720p : Sound without a picture

![3](https://user-images.githubusercontent.com/14161956/79589279-748cdf00-80d5-11ea-83ca-6e967b480691.jpg)

-- video output :   only (dvi + dvipc ) ....HDMI  not available.

![1](https://user-images.githubusercontent.com/14161956/79589495-c6ce0000-80d5-11ea-9fd6-ad08b1199541.jpg)

![2](https://user-images.githubusercontent.com/14161956/79589511-ce8da480-80d5-11ea-9ae3-a765eb012991.jpg)

-- softcam panel  It only works by sending this file manually ..!! 

( enigma2-plugin-extensions-camofs_17.14_all )

![5](https://user-images.githubusercontent.com/14161956/79618039-44f7ca00-8109-11ea-9a1c-e8e809bd9953.jpg)

-- The front  led is red when working and blue at standby....

--enigma2 log In the attachments

[enigma2_logfile.zip](https://github.com/teamblue-e2/enigma2/files/4493964/enigma2_logfile.zip)

**Comment by arn354** [comment]
teamblue is not maintained for DM520
