### ISSUE TITLE
Receiver encountered a software problem

### ISSUE THREAD

**Issue by Luxemb** [teamblue-e2/enigma2#16]
Hi.
This week they delivered my UHD QUAD 4K GiGABLUE.

My wife initially installed it two days ago without connecting it to the internet/wifi.

So I’m starting the installation again in order to hook it to the home WiFi.

When I get to the network wizard installation, I keep getting the error message “We are really sorry. Your receiver encountered a software problem and needs to be restarted. Please send the logfile/home/root/logs/enigma2_crash_xxxxx.log to team blue.tech. Your receiver restarts in 10seconds”

Then it keeps restarting and showing the same message .

Could you please advise how to get around this software problem.

Thank you.

Kafui
Luxembourg
Pls call me on mobile number: +352 691 285 326

Steps from START WIZARD,
-OK
-Use the Wizard to set up basic features 
-Ok
-check the internet connection 
-Ok
-Your receiver does not have internet connection 
-EXIT

From Wizard:
-Press OK to start configuring your network
-“We are really sorry. Your receiver encountered a software problem and needs to be restarted. Please send the logfile/home/root/logs/enigma2_crash_xxxxx.log to team blue.tech. Your receiver restarts in 10seconds”

- Press OK to start configuring your network 
-same error message from above

**Comment by arn354** [comment]
1.) Please upload the crashlog.
2.) make sure you use the latest available image from https://images.teamblue.tech/6.4-release/index.php and tell us which one you flashed/installed.

Skip Network setup in Startwizard - and configure your wlan afterwards, making sure you have the required wlan drivers installed - not all are pre-installed. If not pre-installed you need to connect the box at least to setup via network cable.

**Comment by teamblue-e2** [comment]
I figure it's either solved or not important..
