### ISSUE TITLE
zgemma H9.2H

### ISSUE THREAD

**Issue by tittone77** [teamblue-e2/enigma2#18]
**Describe the bug**
cyclic reboot after
[Enigma2-debug-20201231_00-47-56.log](https://github.com/teamblue-e2/enigma2/files/5756067/Enigma2-debug-20201231_00-47-56.log)
![Foto2](https://user-images.githubusercontent.com/76796485/103387346-6ff14500-4b03-11eb-9963-7676ae1acf82.jpeg)

 firmware update

**To Reproduce**
1. zgemma h92h
2. flash using [PKCGsettings+BASEimg] ZGEMMA H9.2H H9S H9T Nemoxyz SATtek Elegance BLUE v2.0 GST1.15.2 ExteP3 SET2019-ver2-SATtekHB-v2.0
3. see the behavior
4. See  the attached error

**Screenshots**
Foto1 and then Foto2 is the displayed error that I received after the flash
![Foto1](https://user-images.gith
![Foto2](https://user-images.githubusercontent.com/76796485/103387389-b9419480-4b03-11eb-8340-c147afd7284c.jpeg)
ubusercontent.com/76796485/103387380-a6c75b00-4b03-11eb-8006-9fbecda7929d.jpeg)
[Enigma2-debug-20201231_00-47-56.log](https://github.com/teamblue-e2/enigma2/files/5756069/Enigma2-debug-20201231_00-47-56.log)

**Additional context**

**Comment by arn354** [comment]
hi, happy new year!
I have no idea from where zgemma h92h is build from - probably not from this repository, as mainly only GigaBlue modifications are within teamblue.
Regards
arn354

**Comment by teamblue-e2** [comment]
Won't support non GigaBlue Hardware!
