### ISSUE TITLE
Problem with HDR channels , teamblue 6.4

### ISSUE THREAD

**Issue by Micipsa4** [teamblue-e2/enigma2#19]
Hello,
I've gigablue ue 4k, with teamblue image 6.4, 
When I run an HDR channel on ASTRA like ses uhd demo and UHD1 by ASTRA tv , the tv philips 4k Detects the HDR signal but the image Becomes pale and à little dark, the problem doesn't exists when i use the internal receiver of my tv, what do you think ? I use teamblue 6.4, last version 2021, thank you in advance

**Comment by teamblue-e2** [comment]
sorry, but I can't reproduce that issue.. Working properly for me.
