### ISSUE TITLE
Compiling job went successfully but device crashes at booting

### ISSUE THREAD

**Issue by N3m0xyz** [teamblue-e2/enigma2#2]
Hi Guys!!
Tried to compile "teamblue" image like I do from many time on other base images ( like openpli or openblackhole ) The compiling job was successfull and teamblue image zip image looks it could be fine.
Unfortunately something went wrong and after flashing the image I have found some crashes on decoder.
The booting was not completed and the device have blue screen with these error-logs ( see the image link below ):    https://i.imgur.com/rDQewQh.jpg

If someonelse should be able to help me or give me some suggest I am very gratefull in advance.
See you soon!! Regards

**Comment by arn354** [comment]
which box? which compile steps? the ones from readme here?

**Comment by arn354** [comment]
well thats why i ask - teamblue has almost no modifications for other boxes then GigaBlue. You need to patch it then or you should build openatv which has zgemma modifications included.
