### ISSUE TITLE
Transcoding

### ISSUE THREAD

**Issue by bigreja** [teamblue-e2/enigma2#4]
Transcoding it's not working, on VLC it gives timeout, normal stream plays very well.

**To Reproduce**
1. Go to WebIF
2. Click on CellPhone icon
3. .m3u downloads
4. Open on VLC 

**Expected behavior**
It should start streaming transcoded channel 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chome
 
**Additional context**
Accessing terminal and executing top command shows processor running at +/- 5% after starting transcoder, so it's not running

This is what i get on enigma debug log
[StreamService] handle command 1:0:1:321:24:36:FFFF0000:0:0:0:
[StreamService]e execBegin 1:0:1:321:24:36:FFFF0000:0:0:0:
[Navigation] recording service: 1:0:1:321:24:36:FFFF0000:0:0:0:
[eDVBResourceManager] allocate channel.. 0024:0036
[eDVBResourceManager] available channel.. 0024:0036
[eDVBResourceManager] found shared channel..
[eDVBServicePMTHandler] allocate Channel: res 0
[eDVBCIInterfaces] addPMTHandler 1:0:1:321:24:36:FFFF0000:0:0:0:
[eDVBChannel] getDemux cap=01
[eDVBServicePMTHandler] ok ... now we start!!
[eDVBServiceRecord] RECORD service event 5
[StreamService] RECORD event for us: *' at 0xaf214a40> >
[eDVBCAService] add demux 0 to slot 1 service 1:0:1:321:24:36:FFFF0000:0:0:0:
[eDVBDemux] open demux /dev/dvb/adapter0/demux0
[eDVBSectionReader] DMX_SET_FILTER pid=0
[eDVBServiceRecord] RECORD service event 6
[eDVBServiceRecord] tuned..
[eDVBDemux] open demux /dev/dvb/adapter0/demux0
[eDVBSectionReader] DMX_SET_FILTER pid=18
[StreamService] RECORD event for us: *' at 0xaf214a40> >
[eDVBChannel] getDemux cap=00
[StreamService] RECORD event for us: *' at 0xaf214a40> >
[eDVBServiceRecord] start streaming...
[StreamService] RECORD event for us: *' at 0xaf214a40> >
[eDVBServicePMTHandler] PATready
[eDVBServicePMTHandler] use pmtpid 0331 for service_id 0321
[eDVBDemux] open demux /dev/dvb/adapter0/demux0
[eDVBSectionReader] DMX_SET_FILTER pid=817
[eDVBDemux] open demux /dev/dvb/adapter0/demux0
[eDVBSectionReader] DMX_SET_FILTER pid=0
[eDVBServiceRecord] RECORD service event 5
[eDVBServiceRecord] start streaming...
[StreamService] RECORD event for us: *' at 0xaf214a40> >
[Config] getResolvedKey config.autolanguage.audio_autoselect2 empty variable.
[Config] getResolvedKey config.autolanguage.audio_autoselect3 empty variable.
[Config] getResolvedKey config.autolanguage.audio_autoselect4 empty variable.
[Config] getResolvedKey config.autolanguage.subtitle_autoselect1 empty variable.
[Config] getResolvedKey config.autolanguage.subtitle_autoselect2 empty variable.
[Config] getResolvedKey config.autolanguage.subtitle_autoselect3 empty variable.
[Config] getResolvedKey config.autolanguage.subtitle_autoselect4 empty variable.
[StreamService] RECORD event for us: *' at 0xaf214a40> >
[eDVBCIInterfaces] gotPMT
[eDVBCAService] don't build/send the same CA PMT twice
[eDVBDemux] open demux /dev/dvb/adapter0/demux0
[eDVBSectionReader] DMX_SET_FILTER pid=817
[eConsoleAppContainer] Starting /usr/bin/grab
[eConsoleAppContainer] Starting /usr/bin/grab
[eConsoleAppContainer] Starting /usr/bin/grab
[eConsoleAppContainer] Starting /usr/bin/grab
[eConsoleAppContainer] Starting /usr/bin/grab
[eConsoleAppContainer] Starting /usr/bin/grab
[OpenWebif] -D- tuner '0' 'DVB-C NIM(3128 FBC)' 'Tuner A'
[OpenWebif] -D- tuner '1' 'DVB-C NIM(3128 FBC)' 'Tuner B'
[OpenWebif] -D- tuner '2' 'DVB-C NIM(3128 FBC)' 'Tuner C'
[OpenWebif] -D- tuner '3' 'DVB-C NIM(3128 FBC)' 'Tuner D'
[OpenWebif] -D- tuner '4' 'DVB-C NIM(3128 FBC)' 'Tuner E'
[OpenWebif] -D- tuner '5' 'DVB-C NIM(3128 FBC)' 'Tuner F'
[OpenWebif] -D- tuner '6' 'DVB-C NIM(3128 FBC)' 'Tuner G'
[OpenWebif] -D- tuner '7' 'DVB-C NIM(3128 FBC)' 'Tuner H'
[OpenWebif] -D- streamList count '1'

log transtreamproxy.log

^[[1;31m[ ERROR]^[[00m[4407] ++nostream count : 0 (../../git/src/Demuxer.cpp, webif_reauest:78) 
^[[1;31m[ ERROR]^[[00m[4407] ++nostream count : 1 (../../git/src/Demuxer.cpp, webif_reauest:78) 
^[[1;31m[ ERROR]^[[00m[4407] ++nostream count : 2 (../../git/src/Demuxer.cpp, webif_reauest:78) 
^[[1;31m[ ERROR]^[[00m[4407] signal no : Interrupt (2) (../../git/src/main.cpp, signal_handler:550) 
^[[1;31m[ ERROR]^[[00m[4632] ++nostream count : 0 (../../git/src/Demuxer.cpp, webif_reauest:78) 
^[[1;31m[ ERROR]^[[00m[4632] ++nostream count : 1 (../../git/src/Demuxer.cpp, webif_reauest:78) 
^[[1;31m[ ERROR]^[[00m[4632] ++nostream count : 2 (../../git/src/Demuxer.cpp, webif_reauest:78) 

It has openvix image installed, but with other images problem is the same team blue 6.3 included.

**Comment by teamblue-e2** [comment]
transcoding should be working again

**Comment by bigreja** [comment]
Is there any build with the fix available?

**Comment by arn354** [comment]
not sure what you mean - i use transcoding.

**Comment by bigreja** [comment]
I have a GigaBlue UHD UE 4K and transcoding never worked for me, I've bought it on 02-2019, as team blue replied, it should be working again, so my question is, is there any build with the fix so I can install and test?

**Comment by teamblue-e2** [comment]
simply check official download of gbue4k tb 6.3-release - see screenshot with working transcoding for SAT 1 HD .

![20-05-_2019_18-17-03](https://user-images.githubusercontent.com/35139687/58036545-a98e5b80-7b2b-11e9-8a28-910c180d8ca2.jpg)

**Comment by bigreja** [comment]
Still not working for me, TeamBlue 6.3 build from 20-05-2019, I will try to get the logs latter.

**Comment by bigreja** [comment]
transtreamproxy.log
[1;31m[  ERROR][00m[4285] ++nostream count : 0 (../../git/src/Demuxer.cpp, webif_reauest:78)
[1;31m[  ERROR][00m[4285] ++nostream count : 1 (../../git/src/Demuxer.cpp, webif_reauest:78)
[1;31m[  ERROR][00m[4285] ++nostream count : 2 (../../git/src/Demuxer.cpp, webif_reauest:78)

Same errors

**Comment by bigreja** [comment]
> simply check official download of gbue4k tb 6.3-release - see screenshot with working transcoding for SAT 1 HD .
> 
> ![20-05-_2019_18-17-03](https://user-images.githubusercontent.com/35139687/58036545-a98e5b80-7b2b-11e9-8a28-910c180d8ca2.jpg)

Can you please tell me what settings are you using on transcoding plugin?

**Comment by bigreja** [comment]
Debug log...


12:35:10.1692 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] handle command 1:0:1:337:2F:36:FFFF0000:0:0:0:
12:35:10.1703 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService]e execBegin 1:0:1:337:2F:36:FFFF0000:0:0:0:
12:35:10.1712 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] recording service: <enigma.eServiceReference; proxy of <Swig Object of type 'eServiceReference *' at 0xb156c938> >
12:35:10.1717 [   ] dvb/dvb.cpp:1085 allocateChannel [eDVBResourceManager] allocate channel.. 002f:0036
12:35:10.1718 [   ] dvb/dvb.cpp:1088 allocateChannel [eDVBResourceManager] available channel.. 002f:0036
12:35:10.1718 [   ] dvb/dvb.cpp:1091 allocateChannel [eDVBResourceManager] found shared channel..
12:35:10.1718 [   ] dvb/pmt.cpp:1059 tuneExt [eDVBServicePMTHandler] allocate Channel: res 0
12:35:10.1718 [   ] dvb_ci/dvbci.cpp:658 addPMTHandler [eDVBCIInterfaces] addPMTHandler 1:0:1:337:2F:36:FFFF0000:0:0:0:
12:35:10.1719 [   ] dvb/dvb.cpp:2099 getDemux [eDVBChannel] getDemux cap=01
12:35:10.1720 [   ] dvb/pmt.cpp:78 channelStateChanged [eDVBServicePMTHandler] ok ... now we start!!
12:35:10.1720 [   ] service/servicedvbrecord.cpp:37 serviceEvent [eDVBServiceRecord] RECORD service event 5
12:35:10.1728 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xb156c158> >
12:35:10.1738 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xb156c158> >
12:35:10.1740 [   ] dvb/cahandler.cpp:285 registerService [eDVBCAService] add demux 0 to slot 1 service 1:0:1:337:2F:36:FFFF0000:0:0:0:
12:35:10.1742 [   ] dvb/demux.cpp:82 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux0
12:35:10.1742 [   ] dvb/demux.cpp:267 start [eDVBSectionReader] DMX_SET_FILTER pid=0
12:35:10.1750 [   ] service/servicedvbrecord.cpp:37 serviceEvent [eDVBServiceRecord] RECORD service event 6
12:35:10.1750 [   ] service/servicedvbrecord.cpp:42 serviceEvent [eDVBServiceRecord] tuned..
12:35:10.1751 [   ] dvb/demux.cpp:82 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux0
12:35:10.1751 [   ] dvb/demux.cpp:267 start [eDVBSectionReader] DMX_SET_FILTER pid=18
12:35:10.1763 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xb156c158> >
12:35:10.1772 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xb156c158> >
12:35:10.1774 [   ] dvb/dvb.cpp:2099 getDemux [eDVBChannel] getDemux cap=00
12:35:10.1781 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xb156c158> >
12:35:10.1792 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xb156c158> >
12:35:10.1793 [   ] service/servicedvbrecord.cpp:328 doRecord [eDVBServiceRecord] start streaming...
12:35:10.1799 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xb156c158> >
12:35:10.1808 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xb156c158> >
12:35:10.2123 [   ] dvb/pmt.cpp:208 PATready [eDVBServicePMTHandler] PATready
12:35:10.2123 [   ] dvb/pmt.cpp:245 PATready [eDVBServicePMTHandler] use pmtpid 0331 for service_id 0337
12:35:10.2124 [   ] dvb/demux.cpp:82 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux0
12:35:10.2124 [   ] dvb/demux.cpp:267 start [eDVBSectionReader] DMX_SET_FILTER pid=817
12:35:10.2136 [   ] dvb/demux.cpp:82 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux0
12:35:10.2137 [   ] dvb/demux.cpp:267 start [eDVBSectionReader] DMX_SET_FILTER pid=0
12:35:10.2497 [   ] service/servicedvbrecord.cpp:37 serviceEvent [eDVBServiceRecord] RECORD service event 5
12:35:10.2498 [   ] service/servicedvbrecord.cpp:328 doRecord [eDVBServiceRecord] start streaming...
12:35:10.2508 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xb156c158> >
12:35:10.2519 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xb156c158> >
12:35:10.2534 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xb156c158> >
12:35:10.2542 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xb156c158> >
12:35:10.2545 [   ] dvb_ci/dvbci.cpp:776 gotPMT [eDVBCIInterfaces] gotPMT
12:35:10.2545 [   ] dvb/cahandler.cpp:624 buildCAPMT [eDVBCAService] don't build/send the same CA PMT twice
12:35:10.2546 [   ] dvb/demux.cpp:82 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux0
12:35:10.2547 [   ] dvb/demux.cpp:267 start [eDVBSectionReader] DMX_SET_FILTER pid=817
12:35:10.6371 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] execEnd 1:0:1:32B:24:36:FFFF0000:0:0:0:
12:35:10.6374 [   ] service/servicedvbrecord.cpp:179 stop [eDVBServiceRecord] stop recording!
12:35:10.6375 [ E ] service/servicedvbrecord.cpp:586 saveCutlist [eDVBServiceRecord] saving cutlist failed because tstools failed
12:35:10.6386 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xb1cea8f0> >
12:35:10.6402 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xb1cea8f0> >
12:35:10.6431 [   ] dvb/cahandler.cpp:333 unregisterService [eDVBCAService] free slot 1 demux 1 for service 1:0:1:32B:24:36:FFFF0000:0:0:0:
12:35:10.6432 [   ] dvb/cahandler.cpp:497 ~eDVBCAService [eDVBCAService] free service 1:0:1:32B:24:36:FFFF0000:0:0:0:
12:35:10.6436 [   ] dvb/dvbtime.cpp:699 DVBChannelStateChanged [eDVBLocalTimerHandler] remove channel 0x13170b0
12:35:10.6437 [   ] dvb/epgcache.cpp:688 DVBChannelStateChanged [eEPGCache] remove channel 0x13170b0
12:35:10.6451 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] Unhandled error in Deferred:
12:35:10.6456 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-22 12:35:10+0200 [-] Unhandled Error

**Comment by arn354** [comment]
all default nothing special.

**Comment by bigreja** [comment]
still not working for me, should I open a new one, or this could be reopened?
I'm using GigaBlue UHD UE 4K with FBC Cable tuner.

**Comment by teamblue-e2** [comment]
You could open a new one, but as it is working normally here - no idea whats wrong on your side.
Are your tuners correctly configured?
Are you able to view and record two different services at the same time?
Do you restore settings? Are you using anything modified regarding transcoding?
Flash teamblue, setup manually 2 tuners - do not restore settings. Make a scan, add a few services to a bouquet, enable debug& twisted log, restart your box, check transcoding. add both logs here.

**Comment by teamblue-e2** [comment]
[1;31m[  ERROR][00m[16632] ++nostream count : 0 (../../git/src/Demuxer.cpp, webif_reauest:78)
[1;31m[  ERROR][00m[16632] ++nostream count : 1 (../../git/src/Demuxer.cpp, webif_reauest:78)
[1;31m[  ERROR][00m[16632] ++nostream count : 2 (../../git/src/Demuxer.cpp, webif_reauest:78)

first three lines are no "real" errors. it simply takes time until the transcoded stream is established.

**Comment by bigreja** [comment]
I install teamblue image on multiboot, no restore was made, I've set up all 8 tuners and did a scan, e can watch one Channel on Tv and other using normal stream, I will enable twisted log and debug log and will post logs this weekend.
Only changed transcoding settings to 720p, 1.5Mbps and 25 frames ps, other settings are default.
I'm a developer but never did anything on enigma, could you tell me what changes were made to "fix" this problem? I've searched latest commits but haven't found nothing related.

**Comment by teamblue-e2** [comment]
there were changes in openwebif. as we build openwebif with no fixed SRC_REV there was an issue in openwebif for a few days. Check the link in openwebif - which url is passed to vlc...
Do not use multitranscodingsetup and transcoding parameters shipped via url. GB-transtreamproxy needs the url like that: http://gbue4k.local:8002/1:0:1:445C:453:1:C00000:0:0:0:

**Comment by bigreja** [comment]
[Arquivo.zip](https://github.com/teamblue-e2/enigma2/files/3217479/Arquivo.zip)
Twisted log
debug log and transtreamproxy log
![1_0_1_337_2F_36_FFFF0000_0_0_0_20190524145359](https://user-images.githubusercontent.com/13135671/58337498-d13c3700-7e3d-11e9-9913-19fccdb92ad6.jpg)
my transcoding settings, VLC is still trying to play stream, I can play normal streams without transcoding and watch another channel with any problem.

URL is in format  http://gbue4k.local:8002/1:0:1:445C:453:1:C00000:0:0:0:
the only diference between normal streaming and transcoding is port number.

**Comment by teamblue-e2** [comment]
contact impex/gigablue

no idea - even using your settings in transcodingsetup it just works here.

20:55:40.2362 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-24 20:55:40+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xadbfd0e0> >
20:55:40.2367 [   ] dvb_ci/dvbci.cpp:776 gotPMT [eDVBCIInterfaces] gotPMT
20:55:40.2368 [   ] dvb/demux.cpp:82 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux1
20:55:40.2369 [   ] dvb/demux.cpp:267 start [eDVBSectionReader] DMX_SET_FILTER pid=96
20:55:40.2392 [   ] dvb/demux.cpp:82 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux1
20:55:40.2393 [   ] dvb/demux.cpp:267 start [eDVBSectionReader] DMX_SET_FILTER pid=97
20:55:40.5634 [   ] dvb/demux.cpp:82 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux1
20:55:40.5636 [   ] dvb/demux.cpp:267 start [eDVBSectionReader] DMX_SET_FILTER pid=98
20:55:40.6876 [   ] dvb/pmt.cpp:1008 SDTScanEvent [eDVBServicePMTHandler] sdt update done!
20:55:40.8837 [   ] service/servicedvbrecord.cpp:570 gotNewEvent [eDVBServiceRecord] now running: LUKE! Die Schule und ich - VIPs gegen Kids (9219 seconds)
20:55:40.8848 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-24 20:55:40+0200 [-] [StreamService] RECORD event for us: <enigma.iRecordableServicePtr; proxy of <Swig Object of type 'ePtr< iRecordableService > *' at 0xadbfd0e0> >
20:55:40.8854 [   ] dvb/demux.cpp:82 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux1
20:55:40.8855 [   ] dvb/demux.cpp:267 start [eDVBSectionReader] DMX_SET_FILTER pid=18
20:55:41.1877 [   ] dvb/pmt.cpp:291 AITready [eDVBServicePMTHandler] AITready
20:55:41.1879 [   ] dvb/pmt.cpp:285 saveData Save Data Len : [251]
20:55:41.1879 [   ] service/servicedvbrecord.cpp:37 serviceEvent [eDVBServiceRecord] RECORD service event 11

**Comment by bigreja** [comment]
Could it be IPV6 related?
found this...
2019-05-24 14:59:01+0200 [-] Timing out client: IPv6Address(TCP, '::ffff:192.168.1.4', 59788)

But I don't have IPV6 active on my MAC, it only has an IPV4 static address.
I don't have access to my router DHCP server, I don't think it has IPV6 support.

I will try to test this "theory"

**Comment by teamblue-e2** [comment]
in teamblue there is an option to disable ipv6.
ipv6 is disabled here.
